"""
Quick Setup Script for CODEX with Judge0
Helps you configure Judge0 integration in 2 minutes
"""

import os
import sys

def print_header(text):
    print("\n" + "=" * 60)
    print(text)
    print("=" * 60 + "\n")

def check_env_file():
    """Check if .env file exists"""
    return os.path.exists('.env')

def read_env():
    """Read current .env file"""
    env_vars = {}
    if check_env_file():
        with open('.env', 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key] = value
    return env_vars

def write_env(env_vars):
    """Write .env file"""
    with open('.env', 'w') as f:
        f.write("# CODEX Configuration File\n")
        f.write("# Generated by quick_setup.py\n\n")
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")

def main():
    print_header("🚀 CODEX QUICK SETUP")
    
    print("This script will help you configure Judge0 for code execution.\n")
    
    # Check current configuration
    env_vars = read_env()
    current_key = env_vars.get('JUDGE0_API_KEY', '')
    
    if current_key and current_key != 'your-key-here':
        print(f"✅ Judge0 API key is already configured!")
        print(f"   Current key: {current_key[:10]}...{current_key[-4:]}")
        print("\nYour app is ready to use!")
        print("\nTo start:")
        print("  python app.py")
        return
    
    print("Choose your Judge0 setup option:\n")
    print("1️⃣  Use RapidAPI (Recommended - Fast & Reliable)")
    print("   • Get free API key in 2 minutes")
    print("   • 50 free executions per day")
    print("   • Perfect for development\n")
    
    print("2️⃣  Use Public API (No Setup)")
    print("   • No signup required")
    print("   • May be slow/unreliable")
    print("   • Good for testing\n")
    
    print("3️⃣  I already have RapidAPI key")
    print("   • Enter your key now\n")
    
    choice = input("Enter your choice (1, 2, or 3): ").strip()
    
    if choice == "1":
        print_header("📋 GET RAPIDAPI KEY")
        print("Follow these steps:\n")
        print("1. Open your browser and go to:")
        print("   https://rapidapi.com/judge0-official/api/judge0-ce\n")
        print("2. Click 'Sign Up' (top right)")
        print("3. Create a free account")
        print("4. Subscribe to the FREE plan (0-50 requests/day)")
        print("5. Copy your API key from the 'X-RapidAPI-Key' field\n")
        
        input("Press Enter after you've copied your API key...")
        
        api_key = input("\nPaste your RapidAPI key here: ").strip()
        
        if not api_key:
            print("\n❌ No key provided. Setup cancelled.")
            return
        
        # Update .env
        env_vars['JUDGE0_API_KEY'] = api_key
        if 'SECRET_KEY' not in env_vars:
            import secrets
            env_vars['SECRET_KEY'] = secrets.token_hex(32)
        if 'DB_TYPE' not in env_vars:
            env_vars['DB_TYPE'] = 'mysql'
        if 'FLASK_ENV' not in env_vars:
            env_vars['FLASK_ENV'] = 'production'
        if 'FLASK_DEBUG' not in env_vars:
            env_vars['FLASK_DEBUG'] = 'False'
        
        write_env(env_vars)
        
        print_header("✅ SETUP COMPLETE!")
        print("Your Judge0 configuration is ready!\n")
        print("To start your app:")
        print("  python app.py\n")
        print("Then open: http://127.0.0.1:5000\n")
        
    elif choice == "2":
        print_header("✅ USING PUBLIC API")
        print("Your app will use the free public Judge0 API.\n")
        print("Note: This may be slower than RapidAPI.\n")
        print("To start your app:")
        print("  python app.py\n")
        print("Then open: http://127.0.0.1:5000\n")
        
    elif choice == "3":
        api_key = input("\nEnter your RapidAPI key: ").strip()
        
        if not api_key:
            print("\n❌ No key provided. Setup cancelled.")
            return
        
        # Update .env
        env_vars['JUDGE0_API_KEY'] = api_key
        if 'SECRET_KEY' not in env_vars:
            import secrets
            env_vars['SECRET_KEY'] = secrets.token_hex(32)
        if 'DB_TYPE' not in env_vars:
            env_vars['DB_TYPE'] = 'mysql'
        if 'FLASK_ENV' not in env_vars:
            env_vars['FLASK_ENV'] = 'production'
        if 'FLASK_DEBUG' not in env_vars:
            env_vars['FLASK_DEBUG'] = 'False'
        
        write_env(env_vars)
        
        print_header("✅ SETUP COMPLETE!")
        print("Your Judge0 configuration is ready!\n")
        print("To start your app:")
        print("  python app.py\n")
        print("Then open: http://127.0.0.1:5000\n")
        
    else:
        print("\n❌ Invalid choice. Setup cancelled.")
        return
    
    print("=" * 60)
    print("📚 For more information, see:")
    print("   JUDGE0_WINDOWS_FIX.md")
    print("=" * 60)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
