version: "3.8"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
      POSTGRES_DB: judge0
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  api:
    image: judge0/judge0:latest
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "2358:2358"
    environment:
      - DATABASE_URL=postgres://judge0:judge0@db:5432/judge0
      - REDIS_URL=redis://redis:6379
      - ENABLE_DEBUG=true
      - ALLOW_ORIGIN=*
volumes:
  db-data:
